/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quan_ly_benh_vien.View.Main.Component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import quan_ly_benh_vien.Model.Model_Menu;
import quan_ly_benh_vien.View.Login.Component.Login;

/**
 *
 * @author khue1
 */
<<<<<<< HEAD
=======

>>>>>>> 96401bc93da2f4db16dbd96e6dd672a4297133c6
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
<<<<<<< HEAD
    private EventMenuSelected event;
=======
       private EventMenuSelected event;
>>>>>>> 96401bc93da2f4db16dbd96e6dd672a4297133c6

    public void addEventMenuSelected(EventMenuSelected event) {
        this.event = event;
        listMenu1.addEventMenuSelected(event);
    }
<<<<<<< HEAD

    public Menu() {
        initComponents();
        LbTaiKhoan.setText("Xin chào " + Login.xacNhanDangNhap);
=======
    
    public Menu() {
        initComponents();
        LbTaiKhoan.setText("Xin chào "+Login.xacNhanDangNhap);
>>>>>>> 96401bc93da2f4db16dbd96e6dd672a4297133c6
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();

    }

    //tạo mục menu , phân vùng quản lý 
<<<<<<< HEAD
    private void init() {
        listMenu1.addItem(new Model_Menu("1", "Đặt Lịch", Model_Menu.MenuType.MENU));
        if (Login.xacNhanUser != null && Login.xacNhanUser.equals("admin")) {
            listMenu1.addItem(new Model_Menu("2", "Ca Khám", Model_Menu.MenuType.MENU));
            listMenu1.addItem(new Model_Menu("4", "Quản lý bệnh nhân", Model_Menu.MenuType.MENU));
            listMenu1.addItem(new Model_Menu("3", "Quản lý bác sĩ", Model_Menu.MenuType.MENU));

        } else if (Login.xacNhanUser.equals("doctor")) {
            listMenu1.addItem(new Model_Menu("2", "Ca Khám", Model_Menu.MenuType.MENU));
            listMenu1.addItem(new Model_Menu("3", "Quản lý bệnh nhân", Model_Menu.MenuType.MENU));
            listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
        } else {
            listMenu1.addItem(new Model_Menu("", "", Model_Menu.MenuType.TITLE));
            listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
            listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
        }

=======

    private void init() {
        listMenu1.addItem(new Model_Menu("1", "Đặt Lịch", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("2", "Quản lý bác sĩ", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("3", "Quản lý bệnh nhân", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
>>>>>>> 96401bc93da2f4db16dbd96e6dd672a4297133c6
        //tách ô 
        listMenu1.addItem(new Model_Menu("", "My Data", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
        listMenu1.addItem(new Model_Menu("8", "Thông tin tài khoản", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("10", "Thông tin liên hệ", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("5", "Đăng xuất", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("", "", Model_Menu.MenuType.EMPTY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new javax.swing.JPanel();
        LbTaiKhoan = new javax.swing.JLabel();
        listMenu1 = new quan_ly_benh_vien.View.Main.Component.ListMenu<>();

        setBackground(new java.awt.Color(204, 204, 204));

        panelMoving.setOpaque(false);

        LbTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        LbTaiKhoan.setText("Application");

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LbTaiKhoan)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LbTaiKhoan)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
<<<<<<< HEAD
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }
=======
protected void paintChildren(Graphics grphcs) {
    Graphics2D g2 = (Graphics2D) grphcs;
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    GradientPaint g = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
    g2.setPaint(g);
    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
    g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
    super.paintChildren(grphcs);
}
>>>>>>> 96401bc93da2f4db16dbd96e6dd672a4297133c6

    private int x;
    private int y;

    public void initMoving(JFrame fram) {
<<<<<<< HEAD
        panelMoving.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }

        });
        panelMoving.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                fram.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }
=======
    panelMoving.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent me) {
            x = me.getX();
            y = me.getY();
        }

    });
    panelMoving.addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent me) {
            fram.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
        }
    });
}
>>>>>>> 96401bc93da2f4db16dbd96e6dd672a4297133c6
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbTaiKhoan;
    private quan_ly_benh_vien.View.Main.Component.ListMenu<String> listMenu1;
    private javax.swing.JPanel panelMoving;
    // End of variables declaration//GEN-END:variables
}
